server:
  port: 8086
  servlet:
    context-path: krovotarot

springdoc:
  swegger-ui:
    enabled: true

spring:
  application:
   name: KrovoTarot
  data:
    mongodb:
      uri: mongodb://localhost:27017/tarot_db
      username: ${mongo_username:none}
      password: ${mongo_password:none}
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tarot_auth
    username: ${pg_username:none}
    password: ${pg_password:none}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

minio:
  endpoint: http://localhost:9100
  access-key: ${minio_username:none}
  secret-key: ${minio_password:none}
  bucket-name: tarot

prediction:
  type: simple

random:
  service:
    type: simple
  simple:
    algorithm: DRBG
    personalization-string: "KrovoTarot Random Generator"
    strength: 256
    properties:
      - property:
          name: securerandom.drbg.config
          value: HMAC_DRBG, SHA-384
  site:
    selected: random-org
    random-org:
      api-key: ${random_org_api_key:none}
