server:
  port: 8086

spring:
  application:
   name: KrovoTarot
  data:
    mongodb:
      uri: mongodb://localhost:27017/tarot_db
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tarot_auth
    username: ${db.username:none}
    password: ${db.password:none}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

